import os
print( '\033[1;49;97m' + "")
print('     #######                                               #        ######')
print('     #                                                     #       #      #')
print('     #                                                   #####    #        #')
print('     ######    ####     ####    ###   #    #   ######      #      #        #')
print('     #         #   #   #        #      #  #    #    #      #      ##########')
print('     #######   #   #    ####    #        #     ######      #      ####  ####')
print('                                        #      #                  ###    ###')
print('                                       #       #                  ##########')
print('')
print('\033[1;49;96m' + "[!] " + '\033[3;49;92m' + "PA$SW0RD " + '\033[9;49;34m'+ "ENCR3PTER" + '\033[0;0;0m' + "   [!] Don't input '~'")
print("")
print('\033[1;49;97m' + "[!]" + '\033[5;49;91m' + " GENERATING CRYPTOGRAPHIC KEYS..." + "\n")
os.system("python3 in.py > ind.txt")                                                    #Run random indexes for KEY#2
os.system("python3 Rand.py > output.txt")
print('\033[0;0;0m' +  '\033[2;49;92m' + "[!] KEYS GENERATED")
print("")
print('\033[1;49;92m' + "[!]" + " ENCRYPTING..." + '\033[0;0;0m' + '\033[1;49;97m')
print("")
os.system("g++ Enc.cpp -o RUN")
os.system("./RUN > keys.txt")
os.system('cat clear.txt > ind.txt | cat clear.txt > output.txt | cat clear.txt > text.txt')        #clear the text documents used by replacing them with empty document
os.system("java replacer.java > Fkeys.txt")
#os.system("cat clear.txt > keys.txt")
os.system("java keyenc.java > Skeys.txt")
os.system("cat clear.txt > Fkeys.txt")
print('\033[2;49;92m' + "\n[!]DONE" + "\n")
